name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.

  - type: input
    id: version
    attributes:
      label: Version
      description: "Run `npx @bank-mcp/server --version` to get this"
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: Provider
      options:
        - Enable Banking (PSD2)
        - Teller (US)
        - Plaid (US/CA/EU)
        - Tink (EU)
        - Mock
        - N/A
    validations:
      required: true

  - type: dropdown
    id: client
    attributes:
      label: MCP Client
      options:
        - Claude Code
        - Claude Desktop
        - Cursor
        - VS Code (Copilot)
        - Windsurf
        - Codex CLI
        - Gemini CLI
        - Zed
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly. What did you expect vs what actually happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Configured bank-mcp with Enable Banking
        2. Asked Claude "show my transactions"
        3. Got error: ...

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any error output (redact credentials!)
      render: text

  - type: input
    id: node-version
    attributes:
      label: Node.js version
      placeholder: "22.0.0"

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "macOS 15.2 / Ubuntu 24.04 / Windows 11"
